### ISSUE TITLE
Add a copiable atom type

### ISSUE THREAD

**Issue by moulins** [servo/string-cache#195]
The `Atom` type is not `Copy` (from what I understand of the source code, because of the need to drop unused atoms), which make it not as usable as it could be.

In a lot of projects (like on-off CLI utilities, etc), we don't really care about dropping unused atoms, so we don't actually need the `Drop` implementation and `Atom` could in principle implement `Copy`.

Currently, I use my own type, which is a very hacky implementation of this idea:
```rust
//RawAtom is the type generated by string_cache
use interning_raw::RawAtom as RawAtom;
use std::ops::Deref;
use std;

//A struct without the PhantomData field, so that we can implement Copy
#[derive(Copy, Clone)]
pub struct Atom {
	pub unsafe_data: u64
}

impl Deref for Atom {
	type Target = str;

	fn deref(&self) -> &Self::Target {
		assert_eq!(std::mem::size_of::<Atom>(), std::mem::size_of::<RawAtom>());
		//Horribly unsafe, but it *should* work,
		//as the second field of RawAtom is zero-sized
		//and shouldn't affect the in-memory representation
		unsafe {
			std::mem::transmute::<&Atom, &RawAtom>(self)
		}.deref()
	}
}

impl<'a> From<&'a str> for Atom {
	fn from(val: &str) -> Atom {
		let raw: RawAtom = val.into();
		let atom = Atom { unsafe_data: raw.unsafe_data };

		//We leak the RawAtom, so that its (potential) storage isn't deallocated
		std::mem::forget(raw);
		atom
	}
}

//Implementations of Eq, Hash, etc which mirror those in string_cache::atom
```
Obviously, it's not ideal:
- it's an awful hack, depending on implementation details;
- I can't use the `atom!` macro, and if I define my own, I can't use it in pattern position:
```rust
macro_rules! my_atom {
	($atom:expr) => {
		//This is not a pattern!
		atom!($atom).into::<$crate::interning::Atom>()
	}
}
```
So, here's my idea:
- add a `CopiableAtom` type, with only the `unsafe_data` field, implementing `Copy`;
- when constructing a dynamic `CopiableAtom`, leak the underlying data to ensure it will never be dropped;
- add a knob to the `AtomType` builder to choose whether to create an `Atom` or a `CopiableAtom`; for example:
```rust
string_cache_codegen::AtomType::new_copiable("foo::FooAtom", "foo_atom!")...
//or
string_cache_codegen::AtomType::new("foo::FooAtom", "foo_atom!").copiable()...
```

**Comment by SimonSapin** [comment]
If you don’t care about ever freeing dynamically-allocated atoms (effectively leaking memory), then a lot of things in this library can be simplified like removing reference counting entirely and using a standard `HashSet`. You might end up with a different design.

Rather than trying to support both designs in the same library, I feel you’d be better off forking into a separate library.

**Comment by moulins** [comment]
Even without the reference counting, this library still offers the compile-time machinery (the `atom!` is *extremely* useful, and quite a pain to reimplement from scratch), and small-string optimization.

I'll make a fork, and if the changeset isn't too big, I'll PR back.

Thanks for the help! ;)

**Comment by SimonSapin** [comment]
I don’t have to re-implement `atom!`, you can copy it per the terms of the license.

Also, to be frank, Servo wouldn’t use this so I’d rather not take on the responsibility of maintaining it.

> removing reference counting entirely and using a standard HashSet

Something like…

```rust
#[macro_use] extern crate lazy_static;
extern crate leak;

use std::borrow::{Cow, Borrow};
use std::sync::Mutex;
use std::collections::HashSet;

pub fn insert_dynamic(s: Cow<str>) -> &'static String {
    /// Wrapper type to implement `Borrow`, since `&'static String` itself doesn’t.
    #[derive(Hash, Eq, PartialEq)]
    struct LeakedString(&'static String);

    impl Borrow<str> for LeakedString {
        fn borrow(&self) -> &str { self.0 }
    }

    lazy_static! {
        static ref DYNAMIC_ATOMS: Mutex<HashSet<LeakedString>> = Mutex::new(HashSet::new());
    }

    let mut set = DYNAMIC_ATOMS.lock().unwrap();

    // FIXME: take advantage of https://github.com/rust-lang/rfcs/pull/1769
    // when it becomes available
    // to replace two hash table lookups (`get` and `insert`) when we end up inserting,
    // without allocating unnecessarily when we end up reusing an existing `String`.

    if let Some(leaked) = set.get(&*s) {
        return leaked.0
    }

    // Allocating this `Box` has extra cost, but it enables representing a string
    // with a single thin pointer.
    let s = leak::Leak::leak(Box::new(s.into_owned()));
    set.insert(LeakedString(s));
    s
}
```

**Comment by SimonSapin** [comment]
Closing as I think we won’t be supporting `Copy` atoms in this repository, but feel free to discuss further.

**Comment by moulins** [comment]
In fact, I had some similar code, but in the end I stumbled upon the need for matching on atoms, which led me here. My code already used an atom type implementing `Copy`, and removing it would add a ton of boilerplate (and probably would entail some design changes).


I still think that this would be a valuable addition, and I understand if you don't want to maintain it. As such, I won't make a PR, but if you want to take a look, the changes are [here](https://github.com/moulins/string-cache).

The implementation is straight-forward: I created a new type `CopiableAtom` identical to `Atom`, except it doesn't have a `Drop` implementation (it still increments the reference count however).
This may theoretically pose issues, as we could *potentially* overflow the reference count by creating 2**63 `CopiableAtom`s, but the other alternatives were either:
- use a sentinel value (like `-1`) in the refcount to indicate a leaked value, and massively complexifying the refcount manipulation;
- add a `leaked` flag to the `StringCacheEntry`, and checking it before incrementing the refcount when leaking (but this increase the size of the `StringCacheEntry` struct)

----
P.S. : Do you think it's worth the hassle to use the inline representation instead of the pointer to the static table for small static atoms?

**Comment by SimonSapin** [comment]
If you have `Copy` which by nature does not increment a reference count, it seems weird to me to have `Clone` do so. And if you’re forking the library anyway and your code doesn’t use both types of atoms, it seems like needless work to keep both.

Regarding static atoms that are also small enough to be inline, one constraint is that the `atom!(…)` macro needs to generate at compile-time a `u64` value that matches their run-time memory representation, and the representation of inline atoms depends on endianness.

**Comment by moulins** [comment]
I think I didn't explain well; `Clone` doesn't increment the refcount, but if you have some code like this:
```rust
for _ in 0..100 {
  let atom: CopiableAtom = "a long string".into();
}
```
the refcount will be incremented a hundred times.

(And yes, I will probably rework the internals at some point to better suit my needs, but for now it's less work to keep the refcount mechanism.)

----
> Regarding static atoms that are also small enough to be inline, one constraint is that the atom!(…) macro needs to generate at compile-time a u64 value that matches their run-time memory representation, and the representation of inline atoms depends on endianness.

Oh, I didn't think about that... I suppose one could generate one macro for each endianness (behind appropriate `cfg` flags) with the correct representation, but that's a lot of work for a small gain. Too bad, I guess.

**Comment by moulins** [comment]
Side remark: as inline atom representation depends on endianness, do [these tests](https://github.com/servo/string-cache/blob/4a027b0c080a268886ff4afb879bb22f16d5db38/src/atom.rs#L801-L803) only work on little-endian targets? Although I suppose we don't care much as nobody will run the test suite on a big-endian machine...

**Comment by SimonSapin** [comment]
Correct, these tests would fail on big-endian. For a long time the library itself wouldn’t compile on those platforms…
