### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by mohd-akram** [servo/string-cache#205]
I get the following error when building on macOS 10.13.4 using Rust 1.25.0:

```
error: failed to run custom build command for `string_cache v0.7.2 (file:///Users/mohamed/Downloads/string-cache)`
process didn't exit successfully: `/Users/mohamed/Downloads/string-cache/target/debug/build/string_cache-c547615f76cbab49/build-script-build` (signal: 6, SIGABRT: process abort signal)
--- stderr
dyld: Library not loaded: @rpath/libproc_macro-982dc7a0685c08f6.dylib
  Referenced from: /Users/mohamed/Downloads/string-cache/target/debug/build/string_cache-c547615f76cbab49/build-script-build
  Reason: image not found
```

**Comment by emilio** [comment]
cc @SimonSapin

**Comment by SimonSapin** [comment]
Is your Rust installed without rustup? This looks similar to https://github.com/servo/html5ever/issues/342, a work-around might be to use `LD_LIBRARY_PATH=$(rustc --print sysroot)/lib` (or use rustup)

**Comment by mohd-akram** [comment]
Yes, I'm using MacPorts. I fixed this by adding the following to `~/.profile`:

    export DYLD_LIBRARY_PATH=/opt/local/lib/rustlib/x86_64-apple-darwin/lib:$DYLD_LIBRARY_PATH

This seems like a cargo/rustc problem. It's not properly linking the build script. It links to `@rpath/libproc_macro-982dc7a0685c08f6.dylib` but I don't see a `LC_RPATH` when doing `otool -l`, which should be `$(rustc --print sysroot)/lib`. This is fixed by doing:

    install_name_tool -add_rpath $(rustc --print sysroot)/lib /path/to/build-script-build
