### ISSUE TITLE
Why does not Atom implements Copy?

### ISSUE THREAD

**Issue by akurdyukov** [servo/string-cache#211]
I'm using Atoms in my code and now I have a lot of pieces like `some_atom.clone()`  while passing Atoms around. Is there any reason why https://doc.rust-lang.org/std/marker/trait.Copy.html is not implemented for Atom?

**Comment by jdm** [comment]
Clone has a [nontrivial implementation](https://github.com/servo/string-cache/blob/master/src/atom.rs#L334-L351), so it is not possible to copy Atom values around in memory safely.

**Comment by SimonSapin** [comment]
A different design choice (which we won’t make in this library but might be valid for some applications) would be to never free dynamically-allocated atoms. Then reference counting wouldn’t be needed, and atoms could be `Copy`. Of course the trade-off is memory leaks.
