### ISSUE TITLE
Slim down crate by removing build script and build-deps

### ISSUE THREAD

**Issue by jonasbb** [servo/string-cache#225]
I noticed this crate has a build script which is only used to generate files for the tests, but not for the main library. This is unfortunate, as this pulls in a lot of heavy dependencies for anybody not using `string_cache_codegen`.

The reason is that the build script uses `string_cache_codegen`, therefore this is also a build dependency of this crate. Transitively this also pulls in all of `phf_generator` and old versions of `rand`. It would be great if this build dependency could be removed and the tests implemented somehow else.

**Comment by SimonSapin** [comment]
It’s not just tests, I would expect almost all users of `string_cache` to also use `string_cache_codegen` so I’m not sure this would really help.

**Comment by jonasbb** [comment]
string-cache is, when searching, *the* crate for string interning. So I'm not sure if all uses really make use of the pre-built dictionary feature. Instead, the main use case might be memory saving by deduplicating strings and faster string comparisons.

One data point is, there are [only 6 dependencies on `string_cache_codegen`](https://crates.io/crates/string_cache_codegen/reverse_dependencies) compared to [22 dependencies on `string_cache`](https://crates.io/crates/string_cache/reverse_dependencies).

**Comment by dekellum** [comment]
I had a theory on how to improve this, and ended up making the changes to prove it:

#226 preserves all testing strategy and benchmarks, while moving the codegen requirements to a non-released sub-package.  

Other then the volume of code moved, is there much downside to this change, even if some definition of _most_ users will still want the codegen?
