### ISSUE TITLE
Plan to use parking lot?

### ISSUE THREAD

**Issue by kdy1** [servo/string-cache#242]
Hi. I'm working to improve the performance of swc (https://swc.rs) ​

I profiled my bundler, and found that pthread_wait is consuming lots of time.
So I forked this and switched to parking_lot, and it results in a big difference.
(Fork: https://github.com/swc-project/string-cache)

(Total time: 165 ms => 153ms)

Before:
![image](https://user-images.githubusercontent.com/29931815/136515206-edb74cba-977b-4646-9bba-60e4e7f32e4a.png)

After:
![image](https://user-images.githubusercontent.com/29931815/136515124-08207056-9912-48ad-8c14-c7fe7e041532.png)

I will send a PR if you are okay with using parking lot.
If not, I'll just maintain a fork.

**Comment by jdm** [comment]
I would merge that.

**Comment by kdy1** [comment]
@jdm Thanks! I made the PR. https://github.com/servo/string-cache/pull/243
