### ISSUE TITLE
QualName should have a prefix member

### ISSUE THREAD

**Issue by Ms2ger** [servo/string-cache#26]
There doesn't seem to be a good reason to omit that.

**Comment by chotchki** [comment]
@kmcallister would this be considered an easy fix?

**Comment by SimonSapin** [comment]
> Indeed not with HTML syntax

Correction: the HTML parser does emit non-empty prefixes in some cases: https://html.spec.whatwg.org/multipage/#adjust-foreign-attributes

**Comment by nicoburns** [comment]
Closing as `string_cache` no longer has a `QualName` type (since the `0.3.0` in Nov 2016). Furthermore, the [`QualName` type in markup5ever](https://docs.rs/markup5ever/latest/markup5ever/interface/struct.QualName.html) which replaced it has a prefix member.
