### ISSUE TITLE
Implement Deref for Atom → str

### ISSUE THREAD

**Issue by frewsxcv** [servo/string-cache#75]
Disclaimer: I have yet to read through the source code for this project; my only interactions with it have been through servo/servo

It'd be really convenient to be able to do `&atom` instead of `atom.as_slice()` everywhere to get a `str`. It'd greatly increase the ergonomics with utilizing this library

**Comment by frewsxcv** [comment]
If this doesn't make sense to do, please let me know, I'd be curious why

**Comment by kmcallister** [comment]
Sounds good to me. There are probably other places where we should modernize our APIs.
